app_internal_ip_address: "192.168.2.17"
db01_internal_ip_address: "192.168.2.9"
db02_internal_ip_address: "192.168.2.32"
gitlab_internal_ip_address: "192.168.2.10"
main_instance_external_ip_address: "62.84.119.170"
monitoring_internal_ip_address: "192.168.2.23"
runner_internal_ip_address: "192.168.2.6"