- hosts: wordpress
  become: yes
  become_user: root
  remote_user: ubuntu
  environment:
    LANGUAGE: en_US
    LC_ALL: en_US.UTF-8

  tasks:
    - include_vars: ../variables.yml

    - name: Updating installed apt packages
      apt:
        upgrade: no
        update_cache: yes

    - name: Installing apache2, mysql, php and other packages
      ansible.builtin.apt:
        name:
          - apache2
          - ghostscript
          - libapache2-mod-php
          - mysql-server
          - php
          - php-bcmath
          - php-curl
          - php-imagick
          - php-intl
          - php-json
          - php-mbstring
          - php-mysql
          - php-xml
          - php-zip
          - git
        state: present
        update_cache: true

    - name: chmod /var/www
      ansible.builtin.file:
        path: /var/www
        owner: www-data

    - name: Downloading the latest version of WordPress
      shell:
        cmd: curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx -C /var/www

    - name: Creating a WordPress configuration file
      copy:
        dest: /etc/apache2/sites-available/wordpress.conf
        content: |
          <VirtualHost *:80>
            DocumentRoot /var/www/wordpress
            <Directory /var/www/wordpress>
              Options FollowSymLinks
              AllowOverride Limit Options FileInfo
              DirectoryIndex index.php
              Require all granted
            </Directory>
            <Directory /var/www/wordpress/wp-content>
              Options FollowSymLinks
              Require all granted
            </Directory>
          </VirtualHost>

    - name: a2ensite wordpress
      command: a2ensite wordpress

    - name: a2dissite 000-default
      command: a2dissite 000-default

    - name: Restarting apache2 daemon
      systemd:
        name: apache2
        state: restarted
        enabled: yes

    - name: Renaming/copying the WordPress configuration file
      command: sudo -u www-data cp /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php

    - name: Updating WordPress host
      command: sudo -u www-data sed -i 's/localhost/{{ db01_internal_ip_address }}/' /var/www/wordpress/wp-config.php

    - name: Updating WordPress database
      command: sudo -u www-data sed -i 's/database_name_here/wordpress/' /var/www/wordpress/wp-config.php

    - name: Updating WordPress username
      command: sudo -u www-data sed -i 's/username_here/wordpress/' /var/www/wordpress/wp-config.php

    - name: Updating WordPress password
      command: sudo -u www-data sed -i 's/password_here/wordpress/' /var/www/wordpress/wp-config.php

    - name: Adding `WP_SITEURL` to WordPress configuration
      lineinfile:
        path: /var/www/wordpress/wp-config.php
        line: define( 'WP_HOME', 'https://www.sergey-belov.ru' );

    - name: Adding `WP_SITEURL` to WordPress configuration
      lineinfile:
        path: /var/www/wordpress/wp-config.php
        line: define( 'WP_SITEURL', 'https://www.sergey-belov.ru' );

    - name: Including a shared Docker task
      include_role:
        name: '/Users/sergey.belov/PycharmProjects/Netology_DevOps/dvpspdc-3-graduate/ansible/roles/shared'
        tasks_from: docker

    - name: Including a shared 'Node exporter' task
      include_role:
        name: '/Users/sergey.belov/PycharmProjects/Netology_DevOps/dvpspdc-3-graduate/ansible/roles/shared'
        tasks_from: node-exporter