- name: Synchronization
  copy:
    src: ../stack/
    dest: "/opt/stack/"
    owner: root
    group: root
    mode: 0644
  become: true

- name: Pulling all images in compose
  command: docker-compose -f /opt/stack/docker-compose.yaml pull

- name: Taking all services in compose up
  command: docker-compose -f /opt/stack/docker-compose.yaml up -d